### ISSUE TITLE
Desktop app not loading after update

### ISSUE THREAD

**Issue by sain2424** [tahnik/devRantron#203] opened 2017-10-09 06:11 UTC
Logged in after update and nothing happens. I keep getting blank page. I use MAC OSX v 10.11.3.

**Comment by tahnik** [comment] 2017-10-09 07:14
@sain2424 sorry to hear that, do you know what was your previous version? Also, does tapping F12 opens the devtools? If so, please give us a screenshot so that we can understand where the bug is coming from.

**Comment by sain2424** [comment] 2017-10-09 08:59
F12 doesn't load devtools and I dont know the previous version. I think I downloaded it on last Friday or Saturday, so maybe one version before this.

**Comment by tahnik** [comment] 2017-10-09 10:17
I have not been able to reproduce the problem, unfortunately. But the following should reset the cache and restore the application:

With a terminal, remove the devrantron folder located in /Users/<user>/Library/Application Support/

Please let me know if that works.

**Comment by sain2424** [comment] 2017-10-09 11:12
Removed folder. Logged in and same problem again. This time F12 worked and here's screenshot.

https://imgur.com/a/xOWOl

**Comment by tahnik** [comment] 2017-10-09 11:14
@sain2424 do you have an avatar in devRant?

**Comment by sain2424** [comment] 2017-10-09 11:19
yes

**Comment by sain2424** [comment] 2017-10-09 11:21
https://www.devrant.io/users/sain2424

**Comment by tahnik** [comment] 2017-10-09 11:27
@sain2424 Hm I just tried devRantron on my friends MacBook and I cannot reproduce it there either. He used his own account to log in.

One last way you could help me is to zip the devrantron folder in Application Support folder and send it to me personally at tahnik@live.co.uk. Please keep in mind that I will have access to your account for a while because you are logged in. But that is up to you if you want to share and find out what is causing the bug.

Another thing you could do is that you could make sure that you are using the latest version. You can download it from here: https://github.com/tahnik/devRantron/releases/tag/v1.4.1

**Comment by sain2424** [comment] 2017-10-10 10:15
I am using latest version. I have sent you the file.

**Comment by tahnik** [comment] 2017-10-10 10:42
Aha, thank you so much! I figured it out. That was one hell of a bug.

Basically, one of the users that commented you rant has deleted their account. So when the app's notification was trying to fetch the avatar of the user that commented, it was failing. Never took that into consideration before!

I will release an update by today with some other small bugfixes and let you know. Thanks again!

**Comment by sain2424** [comment] 2017-10-11 03:39
Glad I could help.

**Comment by sain2424** [comment] 2017-10-11 03:45
I am also trying to load devRantron development files. Cloned, did npm install then npm start. It loaded at first but not loading now. Could it be related?

**Comment by tahnik** [comment] 2017-10-11 07:06
I just did a fix and merged it to master. It could be related. Any luck with a screenshot of the console?

**Comment by sain2424** [comment] 2017-10-11 12:17
Pulled from master, and I can finally log in. When will it be available for desktop version?

**Comment by hex2f** [comment] 2017-10-11 12:19
@sain2424 very soon

**Comment by tahnik** [comment] 2017-10-12 14:48
@sain2424 can you verify that the latest update works?

**Closed as completed** 2017-10-21 08:15 UTC
Labels: bug
